#pragma once

#include "SparkFun_Extensible_Message_Parser.h"

#define NM_PROTOCOL_SYN_BYTE1 0xaa
#define NM_PROTOCOL_SYN_BYTE2 0x44
#define NM_PROTOCOL_SYN_BYTE3 0x18
#define NM_PROTOCOL_HEADER_LEN 20
#define NM_PROTOCOL_CRC_LEN 4
#define NM_PROTOCOL_MSG_ID_INDEX_L 4
#define NM_PROTOCOL_MSG_ID_INDEX_H 5
#define NM_PROTOCOL_MSG_LEN_INDEX_L 12
#define NM_PROTOCOL_MSG_LEN_INDEX_H 13
#define NM_PROTOCOL_MSG_SENDER_INDEX 16
#define NM_PROTOCOL_MSG_TYPE_INDEX 17
#define NM_PROTOCOL_MSG_INTERVAL_INDEX 19

#define NM_PROTOCOL_MSG_SENDER_DEV 0x01
#define NM_PROTOCOL_MSG_SENDER_APP 0x00
#define NM_PROTOCOL_MSG_SENDER_PANNEL 0x03

#define NM_MSG_QUERY_TYPE 0x00
#define NM_MSG_QUERY_RES_TYPE 0x01
#define NM_MSG_SET_TYPE 0x02
#define NM_MSG_SET_RES_TYPE 0x03
#define NM_MSG_ERR_REP_TYPE 0x05

#define NM_MSG_CRC_ERR_REP_ID 0x01
#define NM_MSG_MSG_ID_ERR_REP_ID 0x02
#define NM_MSG_MODULE_ID_ERR_REP_ID 0x03

#define NM_PANNEL_INFO_ID 0x01
#define NM_PROTOCOL_PINFO_MSG_LEN 36	  /// 32
#define NM_PROTOCOL_PINFO_MSG_PACK_LEN 60 /// 56
#define NM_PROTOCOL_PHV_OFFSET (NM_PROTOCOL_HEADER_LEN + 0)
#define NM_PROTOCOL_PFV_OFFSET (NM_PROTOCOL_HEADER_LEN + 8)
#define NM_PROTOCOL_PBR_OFFSET (NM_PROTOCOL_HEADER_LEN + 16)
#define NM_PROTOCOL_PBL_OFFSET (NM_PROTOCOL_HEADER_LEN + 18)
#define NM_PROTOCOL_PBT_OFFSET (NM_PROTOCOL_HEADER_LEN + 20)
#define NM_PROTOCOL_PBV_OFFSET (NM_PROTOCOL_HEADER_LEN + 22)
#define NM_PROTOCOL_PSS_OFFSET (NM_PROTOCOL_HEADER_LEN + 26)

#define NM_PANNEL_CTRL_ID 0x02
#define NM_PROTOCOL_PCTRL_MSG_LEN 8
#define NM_PROTOCOL_PCTRL_MSG_PACK_LEN 32
#define NM_PROTOCOL_PRE_OFFSET (NM_PROTOCOL_HEADER_LEN + 0)
#define NM_PROTOCOL_PPC_OFFSET (NM_PROTOCOL_HEADER_LEN + 1)
#define NM_PROTOCOL_PRC_OFFSET (NM_PROTOCOL_HEADER_LEN + 2)
#define NM_PROTOCOL_PRO_OFFSET (NM_PROTOCOL_HEADER_LEN + 3)
#define NM_PROTOCOL_PEP_OFFSET (NM_PROTOCOL_HEADER_LEN + 4)

#define NM_PANNEL_HOST_ID 0x03
#define NM_PROTOCOL_HOST_MSG_LEN 2
#define NM_PROTOCOL_HOST_MSG_PACK_LEN 26
#define NM_PROTOCOL_HR1_OFFSET (NM_PROTOCOL_HEADER_LEN + 0)
#define NM_PROTOCOL_HR2_OFFSET (NM_PROTOCOL_HEADER_LEN + 1)
#define NM_PROTOCOL_HNS_OFFSET (NM_PROTOCOL_HEADER_LEN + 4)

#define NM_PANNEL_RST_ID 0x04
#define NM_PROTOCOL_RST_RESP_MSG_LEN 2
#define NM_PROTOCOL_RST_RESP_MSG_PACK_LEN 26
#define NM_PROTOCOL_RRST_OFFSET (NM_PROTOCOL_HEADER_LEN + 0)

#define NM_PANNEL_POWER_ID 0x05
#define NM_PROTOCOL_POWER_RESP_MSG_LEN 2
#define NM_PROTOCOL_POWER_RESP_MSG_PACK_LEN 26

#ifdef __cplusplus
extern "C" {
#endif

extern uint8_t txBuffer_temp[NM_PROTOCOL_PINFO_MSG_PACK_LEN];

int message_decode(SEMP_PARSE_STATE *parse, uint8_t *txBuffer);

#ifdef __cplusplus
}
#endif