#ifndef SLAVE_I2C_h
#define SLAVE_I2C_h

#include <stdint.h>

/* Define I2C unit used for the example */
#define I2C_UNIT                        (CM_I2C1)
#define I2C_FCG_USE                     (FCG1_PERIPH_I2C1)
/* Define slave device address for example */
#define DEVICE_ADDR                     (0x11U)

#define SLAVE_TX_BUFFER_SIZE						256
#define SLAVE_RX_BUFFER_SIZE						512
/* Define port and pin for SDA and SCL */
#define I2C_SCL_PORT                    (GPIO_PORT_A)
#define I2C_SCL_PIN                     (GPIO_PIN_03)
#define I2C_SDA_PORT                    (GPIO_PORT_A)
#define I2C_SDA_PIN                     (GPIO_PIN_02)
#define I2C_GPIO_SCL_FUNC               (GPIO_FUNC_49)
#define I2C_GPIO_SDA_FUNC               (GPIO_FUNC_48)


#define I2C_EEI_IRQN_DEF                (INT005_IRQn)
#define I2C_RXI_IRQN_DEF                (INT006_IRQn)
#define I2C_TXI_IRQN_DEF                (INT003_IRQn)
#define I2C_TEI_IRQN_DEF                (INT004_IRQn)

#define I2C_INT_EEI_DEF                 (INT_SRC_I2C1_EEI)
#define I2C_INT_RXI_DEF                 (INT_SRC_I2C1_RXI)
#define I2C_INT_TXI_DEF                 (INT_SRC_I2C1_TXI)
#define I2C_INT_TEI_DEF                 (INT_SRC_I2C1_TEI)


#define NM_PROTOCOL_SYN_BYTE1 0xaa
#define NM_PROTOCOL_SYN_BYTE2 0x44
#define NM_PROTOCOL_SYN_BYTE3 0x18
#define NM_PROTOCOL_HEADER_LEN 20
#define NM_PROTOCOL_CRC_LEN 4
#define NM_PROTOCOL_MSG_ID_INDEX_L 4
#define NM_PROTOCOL_MSG_ID_INDEX_H 5
#define NM_PROTOCOL_MSG_LEN_INDEX_L 12
#define NM_PROTOCOL_MSG_LEN_INDEX_H 13
#define NM_PROTOCOL_MSG_SENDER_INDEX 16
#define NM_PROTOCOL_MSG_TYPE_INDEX 17
#define NM_PROTOCOL_MSG_INTERVAL_INDEX 19

#define NM_PROTOCOL_MSG_SENDER_DEV 0x01
#define NM_PROTOCOL_MSG_SENDER_APP 0x00
#define NM_PROTOCOL_MSG_SENDER_PANNEL 0x03

#define NM_MSG_QUERY_TYPE 0x00
#define NM_MSG_QUERY_RES_TYPE 0x01
#define NM_MSG_SET_TYPE 0x02
#define NM_MSG_SET_RES_TYPE 0x03
#define NM_MSG_ERR_REP_TYPE 0x05

#define NM_MSG_CRC_ERR_REP_ID 0x01
#define NM_MSG_MSG_ID_ERR_REP_ID 0x02
#define NM_MSG_MODULE_ID_ERR_REP_ID 0x03

#define NM_PANNEL_INFO_ID 0x01
#define NM_PROTOCOL_PINFO_MSG_LEN 36	  /// 32
#define NM_PROTOCOL_PINFO_MSG_PACK_LEN 60 /// 56
#define NM_PROTOCOL_PHV_OFFSET (NM_PROTOCOL_HEADER_LEN + 0)
#define NM_PROTOCOL_PFV_OFFSET (NM_PROTOCOL_HEADER_LEN + 8)
#define NM_PROTOCOL_PBR_OFFSET (NM_PROTOCOL_HEADER_LEN + 16)
#define NM_PROTOCOL_PBL_OFFSET (NM_PROTOCOL_HEADER_LEN + 18)
#define NM_PROTOCOL_PBT_OFFSET (NM_PROTOCOL_HEADER_LEN + 20)
#define NM_PROTOCOL_PBV_OFFSET (NM_PROTOCOL_HEADER_LEN + 22)
#define NM_PROTOCOL_PSS_OFFSET (NM_PROTOCOL_HEADER_LEN + 26)

#define NM_PANNEL_CTRL_ID 0x02
#define NM_PROTOCOL_PCTRL_MSG_LEN 8
#define NM_PROTOCOL_PCTRL_MSG_PACK_LEN 32
#define NM_PROTOCOL_PRE_OFFSET (NM_PROTOCOL_HEADER_LEN + 0)
#define NM_PROTOCOL_PPC_OFFSET (NM_PROTOCOL_HEADER_LEN + 1)
#define NM_PROTOCOL_PRC_OFFSET (NM_PROTOCOL_HEADER_LEN + 2)
#define NM_PROTOCOL_PRO_OFFSET (NM_PROTOCOL_HEADER_LEN + 3)
#define NM_PROTOCOL_PEP_OFFSET (NM_PROTOCOL_HEADER_LEN + 4)

#define NM_PANNEL_HOST_ID 0x03
#define NM_PROTOCOL_HOST_MSG_LEN 2
#define NM_PROTOCOL_HOST_MSG_PACK_LEN 26
#define NM_PROTOCOL_HR1_OFFSET (NM_PROTOCOL_HEADER_LEN + 0)
#define NM_PROTOCOL_HR2_OFFSET (NM_PROTOCOL_HEADER_LEN + 1)
#define NM_PROTOCOL_HNS_OFFSET (NM_PROTOCOL_HEADER_LEN + 4)

#define NM_PANNEL_RST_ID 0x04
#define NM_PROTOCOL_RST_RESP_MSG_LEN 2
#define NM_PROTOCOL_RST_RESP_MSG_PACK_LEN 26
#define NM_PROTOCOL_RRST_OFFSET (NM_PROTOCOL_HEADER_LEN + 0)

#define NM_PANNEL_POWER_ID 0x05
#define NM_PROTOCOL_POWER_RESP_MSG_LEN 2
#define NM_PROTOCOL_POWER_RESP_MSG_PACK_LEN 26

#ifdef __cplusplus
extern "C" {
#endif
	
typedef enum
{
	SLAVE_RX = 0,
	SLAVE_RX_DONE,
	SLAVE_TX,
	SLAVE_TX_DONE
}SLAVE_I2C_STATE;

int32_t slave_i2c_init();
void slave_i2c_update();
	
int txBufferAvailable();
int txBufferRead(void);
int txBufferWrite(uint8_t *Buffer, uint16_t length);
#ifdef __cplusplus
}
#endif

#endif
