set(CLANGD_COMPILE_COMMANDS_LINK "${CMAKE_SOURCE_DIR}/build/clangd")

if(EXISTS "${CLANGD_COMPILE_COMMANDS_LINK}" AND
   NOT IS_SYMLINK "${CLANGD_COMPILE_COMMANDS_LINK}")
    message(WARNING
        "Cannot update ${CLANGD_COMPILE_COMMANDS_LINK}: "
        "path exists and is not a symlink"
    )
    return()
endif()

get_filename_component(BINARY_DIR_PARENT "${CMAKE_BINARY_DIR}" DIRECTORY)
get_filename_component(BINARY_DIR_NAME "${CMAKE_BINARY_DIR}" NAME)
get_filename_component(DEFAULT_BUILD_DIR "${CMAKE_SOURCE_DIR}/build" ABSOLUTE)

if(BINARY_DIR_PARENT STREQUAL DEFAULT_BUILD_DIR)
    set(CLANGD_COMPILE_COMMANDS_TARGET "${BINARY_DIR_NAME}")
else()
    set(CLANGD_COMPILE_COMMANDS_TARGET "${CMAKE_BINARY_DIR}")
endif()

file(REMOVE "${CLANGD_COMPILE_COMMANDS_LINK}")
file(CREATE_LINK
    "${CLANGD_COMPILE_COMMANDS_TARGET}"
    "${CLANGD_COMPILE_COMMANDS_LINK}"
    SYMBOLIC
    RESULT CLANGD_LINK_RESULT
)

if(CLANGD_LINK_RESULT EQUAL 0)
    message(STATUS
        "clangd compilation database: "
        "${CLANGD_COMPILE_COMMANDS_LINK} -> ${CLANGD_COMPILE_COMMANDS_TARGET}"
    )
else()
    message(WARNING
        "Failed to update ${CLANGD_COMPILE_COMMANDS_LINK}: "
        "${CLANGD_LINK_RESULT}"
    )
endif()
